name: goreleaser-lint
on:
  push:
    paths:
      - ".goreleaser.yml"
      - .github/workflows/goreleaser.yml

jobs:
  release:
    name: Check GoReleaser
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Lint goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: check